//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBM.WPF.CLIENT.WCFFilterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFFilterService.IFilterService")]
    public interface IFilterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilterService/GetFilter", ReplyAction="http://tempuri.org/IFilterService/GetFilterResponse")]
        MBM.BL.Filter GetFilter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilterService/GetFilter", ReplyAction="http://tempuri.org/IFilterService/GetFilterResponse")]
        System.Threading.Tasks.Task<MBM.BL.Filter> GetFilterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilterService/GetMinMaxValues", ReplyAction="http://tempuri.org/IFilterService/GetMinMaxValuesResponse")]
        MBM.BL.Filter GetMinMaxValues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilterService/GetMinMaxValues", ReplyAction="http://tempuri.org/IFilterService/GetMinMaxValuesResponse")]
        System.Threading.Tasks.Task<MBM.BL.Filter> GetMinMaxValuesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilterService/GetSymbols", ReplyAction="http://tempuri.org/IFilterService/GetSymbolsResponse")]
        string[] GetSymbols();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilterService/GetSymbols", ReplyAction="http://tempuri.org/IFilterService/GetSymbolsResponse")]
        System.Threading.Tasks.Task<string[]> GetSymbolsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFilterServiceChannel : MBM.WPF.CLIENT.WCFFilterService.IFilterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilterServiceClient : System.ServiceModel.ClientBase<MBM.WPF.CLIENT.WCFFilterService.IFilterService>, MBM.WPF.CLIENT.WCFFilterService.IFilterService {
        
        public FilterServiceClient() {
        }
        
        public FilterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MBM.BL.Filter GetFilter() {
            return base.Channel.GetFilter();
        }
        
        public System.Threading.Tasks.Task<MBM.BL.Filter> GetFilterAsync() {
            return base.Channel.GetFilterAsync();
        }
        
        public MBM.BL.Filter GetMinMaxValues() {
            return base.Channel.GetMinMaxValues();
        }
        
        public System.Threading.Tasks.Task<MBM.BL.Filter> GetMinMaxValuesAsync() {
            return base.Channel.GetMinMaxValuesAsync();
        }
        
        public string[] GetSymbols() {
            return base.Channel.GetSymbols();
        }
        
        public System.Threading.Tasks.Task<string[]> GetSymbolsAsync() {
            return base.Channel.GetSymbolsAsync();
        }
    }
}
